# Default values for NGSA memory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  args:
  - --in-memory 
  - --url-prefix
  - /memory
  image:
    repository: ghcr.io/retaildevcrews/ngsa-app
    tag: beta
    imagePullPolicy: Always