prometheus:
  enabled: true

annotations:
  prometheus.io/port: "3031"

nodeSelector:
  agentpool: "npuser01"

memcached:
  resources:
    requests:
      cpu:
      memory: 512Mi

image:
  tag: 1.21.1

git:
  readonly: true
  timeout: 5m

sync:
  state: secret

registry:
  disableScanning: true
